<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商户管理",
                        "menuJump":"列表",
                        "tableName":"shanghu"
                    }
                ],
                "menu":"商户管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"员工管理",
			            "menuJump":"列表",
			            "tableName":"yuangong"
			        }
			    ],
			    "menu":"员工管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"商铺租赁管理",
			            "menuJump":"列表",
			            "tableName":"shopleasing"
			        }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"租赁合同管理",
                        "menuJump":"列表",
                        "tableName":"shopcontract"
                    }
			    ],
			    "menu":"商铺管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"库房管理",
			            "menuJump":"列表",
			            "tableName":"storehouse"
			        }
			    ],
			    "menu":"库房管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "报表",
			                "删除"
			            ],
			            "menu":"市场财务管理",
			            "menuJump":"列表",
			            "tableName":"finance"
			        }
			    ],
			    "menu":"市场财务管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"安全管理管理",
			            "menuJump":"列表",
			            "tableName":"security"
			        }
			    ],
			    "menu":"安全管理管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"卫生管理管理",
			            "menuJump":"列表",
			            "tableName":"hygiene"
			        }
			    ],
			    "menu":"卫生管理管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"卫生值班管理",
			            "menuJump":"列表",
			            "tableName":"beonduty"
			        }
			    ],
			    "menu":"卫生值班管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"账单类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBill"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商铺类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShop"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"材料类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryStuff"
                    }
                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
							"租赁"
			            ],
			            "menu":"商铺租赁管理",
			            "menuJump":"列表",
			            "tableName":"shopleasing"
			        }
					,{
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"租赁合同管理",
	                    "menuJump":"列表",
	                    "tableName":"shopcontract"
	                }
			    ],
			    "menu":"商铺管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"库房管理",
			            "menuJump":"列表",
			            "tableName":"storehouse"
			        }
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
							"出入库",
					        "修改",
					        "删除"
					    ],
					    "menu":"材料管理",
					    "menuJump":"列表",
					    "tableName":"stuff"
					}
			    ],
			    "menu":"库房管理"
			}
			,{
			    "child":[
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"商户账单管理",
					    "menuJump":"列表",
					    "tableName":"bill"
					}
			    ],
			    "menu":"商户账单管理"
			}
			,{
			"child":[
				{
					"buttons":[
						"查看"
						],
						"menu":"安全管理管理",
						"menuJump":"列表",
						"tableName":"security"
					}
				],
				"menu":"安全管理管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"商户",
	    "tableName":"shanghu"
	}
	,
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"安全管理管理",
			            "menuJump":"列表",
			            "tableName":"security"
			        }
			    ],
			    "menu":"安全管理管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"卫生管理管理",
			            "menuJump":"列表",
			            "tableName":"hygiene"
			        }
			    ],
			    "menu":"卫生管理管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"卫生值班管理",
			            "menuJump":"列表",
			            "tableName":"beonduty"
			        }
			    ],
			    "menu":"卫生值班管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"员工",
	    "tableName":"yuangong"
	}
];

var hasMessage = '';
